version: 0.2

phases:
  pre_build:
      commands:
        - echo Logging in to Docker Hub...
        - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PW
        - TAG=$TAG_VERSION
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME-frontend:$TAG ./frontend/todolist
      - docker build -t $IMAGE_REPO_NAME-server:$TAG ./server
      - docker build -t $IMAGE_REPO_NAME-nginx:$TAG ./nginx
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME-frontend:$TAG
      - docker push $IMAGE_REPO_NAME-server:$TAG
      - docker push $IMAGE_REPO_NAME-nginx:$TAG
  artifacts:
    files:
      - '*'

