version: '2.4'

services:
  frontend:
    image: jayko95/study-auth-frontend
    volumes:
      - /app/node_modules
      - ./frontend/todolist:/app
    stdin_open: true
    mem_limit: 512m

  nginx:
    restart: always
    image: jayko95/study-auth-nginx
    ports:
      - "80:80"
    mem_limit: 512m
    links:
      - frontend
      - backend

  backend:
    image: jayko95/study-auth-server
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - .env
    mem_limit: 512m