const userData = [
  {
    groupId: 1,
    name: 'inwoong',
    image: undefined,
    users: [
      {
        userId: 32143,
        firstName: 'inwoong',
        lastName: 'kang',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 32144,
        firstName: 'inwoong',
        lastName: 'kang',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 32145,
        firstName: 'inwoong',
        lastName: 'kang',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 32146,
        firstName: 'inwoong',
        lastName: 'kang',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 32147,
        firstName: 'inwoong',
        lastName: 'kang',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 32148,
        firstName: 'inwoong',
        lastName: 'kang',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 32149,
        firstName: 'inwoong',
        lastName: 'kang',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
    ],
  },
  {
    groupId: 2,
    name: 'joonyoung',
    image: undefined,
    users: [
      {
        userId: 3210,
        firstName: 'jy',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3211,
        firstName: 'jy',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3212,
        firstName: 'jy',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3213,
        firstName: 'jy',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3214,
        firstName: 'jy',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3215,
        firstName: 'jy',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3216,
        firstName: 'jy',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
    ],
  },
  {
    groupId: 3,
    name: 'jsssss',
    image: undefined,
    users: [
      {
        userId: 3210,
        firstName: 'jysssss',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3211,
        firstName: 'jyssss',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3212,
        firstName: 'jysssss',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3213,
        firstName: 'jyssss',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3214,
        firstName: 'jy',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3215,
        firstName: 'jy',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
      {
        userId: 3216,
        firstName: 'jy',
        lastName: 'ko',
        email: 'kanginwoong@hanmail.com',
        password: '',
        signupMethod: 'local',
        role: 'USER',
      },
    ],
  },
];

export default userData;
